---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
  labels:
    app: example-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      serviceAccountName: kubelock-sa
      containers:
      - name: nginx
        image: nginx
      initContainers:
      - name: database-migrations
        env:
        - name: LOCKVALUE
          value: "database-migrations-12345"
        image: ghcr.io/prog76/kubelock:0.0.2-amd64
        command: ["sh", "-c"]
        args:
          - |
            kubelock --name example-app --namespace kubelock --lock-value $LOCKVALUE sh -c 'for i in $(seq 1 5); do echo "executing migrations ($i)"; sleep 5; done'
            echo init container done
