---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
  labels:
    app: example-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      serviceAccountName: kubelock-sa
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
      initContainers:
      - name: database-migrations
        image: ghcr.io/prog76/kubelock:latest-amd64
        command: ["sh", "-c"]
        args:
          - |
            kubelock --name example-app --namespace kubelock --lock-value migration-12345 sh -c 'for i in $(seq 1 5); do echo "executing migrations ($i)"; sleep 5; done'
            echo init container done
