---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubelock-role
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "create", "update"]