name: Test on Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest # This is still the host VM, but we'll use a container for the actual steps
    container: mcr.microsoft.com/devcontainers/go:1-1.23-bookworm
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          go mod download

      - name: Run tests
        run: make test